FROM node:22.9.0-alpine

WORKDIR /app

COPY package*.json ./
COPY tsconfig.json ./

RUN npm install

COPY src/backend ./src/backend

RUN npm run build

EXPOSE 3000

CMD ["node", "dist/backend/server.js"]